spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
#    gateway:
#      routes:
#        - id: r1
#          uri: lb://CUSTOMER-SERVICE
#          predicates:
#             - Path= /customers/**
#        - id: r2
#          uri: lb://INVENTORY-SERVICE
#          predicates:
#            - Path= /products/**

#          uri: lb://CUSTOMER-SERVICE
#          uri: lb://INVENTORY-SERVICE



#        - id: r1
#          uri: http://localhost:8081
#          predicates:
#            - Path= /customers/**
#        - id: r2
#          uri: http://localhost:8082
#          predicates:
#            - Path= /products/**